### ISSUE TITLE
Segmentation fault - invalid memory reference when using DPDchrom

### ISSUE THREAD

**Issue by Xuyuch** [polly-code/DPDchrom#1]
Hi DPDchrom team,
          Thank you for the powerful pipeline. I like the 3D model it created and I want to try your pipeline on my own data. However, It meet some question when I use the dpdchrom. Shows beneath
 ```
./DPDchrom-master/dpdchrom B1.impute.csv 400000 0

 Length of chromosome           1 1                                        480
 Length of chromosome           2 4                                        384
 Length of chromosome           3 5                                        372
 Length of chromosome           4 10                                       319
 Length of chromosome           5 6                                        366
 Length of chromosome           6 9                                        303
 Length of chromosome           7 12                                       292
 Length of chromosome           8 17                                       230
 Length of chromosome           9 2                                        447
 Length of chromosome          10 8                                        316
 Length of chromosome          11 3                                        392
 Length of chromosome          12 7                                        355
 Length of chromosome          13 13                                       294
 Length of chromosome          14 15                                       252
 Length of chromosome          15 16                                       237
 Length of chromosome          16 X                                        414
 Length of chromosome          17 18                                       219
 Length of chromosome          18 14                                       305
 Length of chromosome          19 11                                       297
 Length of chromosome          20 19                                       146
 Length of chromosome          21 Y                                        227

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f0e80a7b51f in ???
#1  0x55ab9289b563 in ???
#2  0x55ab9289d0ad in ???
#3  0x55ab9289d54a in ???
#4  0x55ab9288d2fe in ???
#5  0x7f0e80a62d8f in ???
#6  0x7f0e80a62e3f in ???
#7  0x55ab9288d330 in ???
Segmentation fault
```

The example in the test file works well on my computer and I could visulize the mol2 result.  I attached my own HiC csv file here. Could you please help me to find out the problem? Thanks.
[B1.impute.csv](https://github.com/polly-code/DPDchrom/files/12362059/B1.impute.csv)
Version of fortran compiler I used is GNU FORTUNE 9.4.0 and the  OPENMPI 4.1.1(For some reason, the most up to date GNU FORTUNE  could not complie the DPDchrom).

Thanks again.
Yuchen

**Comment by polly-code** [comment]
Hi Yuchen,
Thank you for reporting the problem with a detailed description. I appreciate it a lot. The problem was caused by the predefined array size. In order to avoid reading the input file twice I hardcoded the size of the array containing Hi-C contact information. The size depends on the chain length. It should cover most of the user cases. But when one selects a coarse resolution, the number of contacts relative to the chain length exceeds the hardcoded value.
Now I increased the value by 2x and now your example works fine. I haven't calculated it completely so please, let me know if you get the final answer.

Best,
Pavel

**Comment by Xuyuch** [comment]
Hi Pavel,
     Thanks for your timely respond and clear explanations. I appreciated it a lot. I tried it with my own datasets and It could work for step 1 now. Unfortunately, it still could not pass to the step 2 and have a error of `STOP error 60:a bead has too high speed along X`. I tried some of my other cells and they all meet the same question. (Or `STOP error 61:a bead has too high speed along Y`). To make things easier, I used the same dataset above and atttached the code here. 
```
 dpdchrom B1.impute.csv 400000 0
 Length of chromosome           1 1                                        480
 Length of chromosome           2 4                                        384
 Length of chromosome           3 5                                        372
 Length of chromosome           4 10                                       319
 Length of chromosome           5 6                                        366
 Length of chromosome           6 9                                        303
 Length of chromosome           7 12                                       292
 Length of chromosome           8 17                                       230
 Length of chromosome           9 2                                        447
 Length of chromosome          10 8                                        316
 Length of chromosome          11 3                                        392
 Length of chromosome          12 7                                        355
 Length of chromosome          13 13                                       294
 Length of chromosome          14 15                                       252
 Length of chromosome          15 16                                       237
 Length of chromosome          16 X                                        414
 Length of chromosome          17 18                                       219
 Length of chromosome          18 14                                       305
 Length of chromosome          19 11                                       297
 Length of chromosome          20 19                                       146
 Length of chromosome          21 Y                                        227
 Expected accuracy is.........   45.0830460     %
 start to write restart, atoms, bonds:       59532      132330

 *********************************************

              DPDchrom

 Some technical information
 Number of nodes              :           1
 Number of nodes in 1 row     :           1

 System information
 Box size X Y Z               :   27.0734310       27.0734310       27.0734310
 Box size at each node        :   27.0734310       27.0734310       27.0734310
 DPD density                  :   3.00000000
 Total number of particles    :       59532
 Types of particles           :    1    2

 Integration information
 Timestep                     :   3.99999991E-02
 Number of steps in 1st stage :        1000
 Number of steps in 2nd stage :      100000

 DPD Parameters
 Sigma                        :   3.00000000
 Gamma                        :   4.50000000
 DPD coeff btw    1 and    1 is   25.0000000
 DPD coeff btw    1 and    2 is   26.7500000
 DPD coeff btw    2 and    2 is   25.0000000

 *********************************************

 stage 1        1000   1.01999533       9.80347395E-04   6.10059404
 stage 1 took   108.29207897400001      s
 stage 1        1000   1.02738357       8.33988190E-04   19.4075279
 stage 1 took   59.878517552999995      s
 stage 1        1000   1.00934267       1.78712606E-03   19.1568279
 stage 1 took   91.365970383000018      s
STOP error 60:a bead has too high speed along X
```
Thanks again for your patience and help. I really appreciate it.

Best,
Yuchen

**Comment by polly-code** [comment]
Sorry to hear about that. This happened because of too many bonds per bead. I am thinking of 2 possible solutions.

1. Increase the resolution. Now it's indicated 400kb. At 100kb this should presumably work fine.
2. If the resolution is critical, you might play with the integration step rate.

If option 1 works for you - then great, if not - I can look closer at option 2.

**Comment by Xuyuch** [comment]
Thanks for reply. I tried to increase the resolution setting in DPDchrom before and the same error still happens even I set the resolution parameter to 100kb 50kb even 20kb. I also tried to increase resolution for my own inpute csv file. For the csv file with a bin size of 100kb, these problems still happens.  Could you please help me with the option 2? Thank you.
